"""partition the corpus into 3 collections (budget / transcript / technical)

Bloque 0 de nivelación de esquema (S10). Particiona el corpus monolítico `chunks`
en tres colecciones con tablas, índices HNSW half-vec y GIN tsvector propios y ciclo
de vida de ingesta independiente (theory Opción B):

- `chunks` se RENOMBRA a `budget_chunks` (preserva datos, FK e índices existentes;
  los índices `chunks_*`/`ix_chunks_*` se renombran por higiene).
- `transcript_chunks` y `technical_doc_chunks` se crean vacías, replicando el esquema
  y los índices de budget_chunks (mismo operador `embedding::halfvec(1536) <=>` alineado
  con `halfvec_cosine_ops`, m=16/ef_construction=128, ver migración 0002).

Revision ID: 0004
Revises: 0003
Create Date: session-10
"""

from __future__ import annotations

from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None

# Tablas nuevas (sin datos): budgets ya existe como rename de chunks.
_NEW_COLLECTIONS = ("transcript_chunks", "technical_doc_chunks")

# Renombrados de índice tras renombrar la tabla (higiene: prefijo coherente).
_INDEX_RENAMES = (
    ("ix_chunks_document_id", "ix_budget_chunks_document_id"),
    ("ix_chunks_chunk_type", "ix_budget_chunks_chunk_type"),
    ("ix_chunks_metadata_gin", "ix_budget_chunks_metadata_gin"),
    ("chunks_embedding_halfvec_idx", "budget_chunks_embedding_halfvec_idx"),
    ("ix_chunks_content_tsv", "ix_budget_chunks_content_tsv"),
)


def _create_collection_table(table: str) -> None:
    """Crea una tabla de colección replicando el esquema de budget_chunks: mismas
    columnas, FK ON DELETE CASCADE, columna generada content_tsv e índices (FK,
    chunk_type, metadata GIN, HNSW half-vec y GIN tsvector)."""
    op.execute(
        f"""
        CREATE TABLE {table} (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            chunk_type VARCHAR(50) NOT NULL,
            content TEXT NOT NULL,
            embedding vector(1536),
            metadata JSONB NOT NULL DEFAULT '{{}}',
            content_tsv tsvector GENERATED ALWAYS AS (to_tsvector('spanish', content)) STORED,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(f"CREATE INDEX ix_{table}_document_id ON {table} (document_id)")
    op.execute(f"CREATE INDEX ix_{table}_chunk_type ON {table} (chunk_type)")
    op.execute(
        f"CREATE INDEX ix_{table}_metadata_gin ON {table} USING gin (metadata)"
    )
    # Índice HNSW half-vec: misma expresión/operator class que budget_chunks (0002),
    # alineada con `embedding::halfvec(1536) <=>` de search_chunks (desalinear =
    # seq scan silencioso, verificar con EXPLAIN ANALYZE).
    op.execute(
        f"CREATE INDEX {table}_embedding_halfvec_idx ON {table} "
        f"USING hnsw ((embedding::halfvec(1536)) halfvec_cosine_ops) "
        f"WITH (m = 16, ef_construction = 128)"
    )
    op.execute(f"CREATE INDEX ix_{table}_content_tsv ON {table} USING gin (content_tsv)")


def upgrade() -> None:
    # 1. Renombra la tabla monolítica → colección de budgets (preserva datos/FK/índices).
    op.rename_table("chunks", "budget_chunks")
    for old, new in _INDEX_RENAMES:
        op.execute(f"ALTER INDEX IF EXISTS {old} RENAME TO {new}")

    # 2. Crea las dos colecciones nuevas (vacías), replicando esquema e índices.
    for table in _NEW_COLLECTIONS:
        _create_collection_table(table)


def downgrade() -> None:
    # Revertir el particionado elimina las colecciones no-budget. La tabla `documents`
    # es compartida: hay que borrar sus filas de transcript/technical para no dejar
    # documentos huérfanos (sin chunks) que rompan la idempotencia por source_path al
    # re-upgrade. Es destructivo a propósito (downgrade revierte a la tabla única budgets).
    op.execute(
        "DELETE FROM documents WHERE document_type IN "
        "('meeting_transcript', 'technical_reference')"
    )
    for table in _NEW_COLLECTIONS:
        op.execute(f"DROP TABLE IF EXISTS {table}")
    for old, new in _INDEX_RENAMES:
        op.execute(f"ALTER INDEX IF EXISTS {new} RENAME TO {old}")
    op.rename_table("budget_chunks", "chunks")
